default_stages: [commit]
repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    verbose: true
    hooks:
      - id: black
        args: [--skip-string-normalization, --line-length=79]
#  - repo: https://github.com/PyCQA/isort
#    rev: 5.10.1
#    verbose: true
#    hooks:
#      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    verbose: true
    hooks:
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace
